### ISSUE TITLE
Where should I put tuto

### ISSUE THREAD

**Issue by MonteiroJ** [chamilo/docs#10]
Bonjour / Hi,

J'ai récemment fait un petit tuto pour modifier le header et footer d'un mail. Je voulais savoir où puis-je le déposer ? 
Cela ne prend que quelques phrases. Mais, je suppose que beaucoup d'utilisateurs sont à la recherche de ça.

I recently did a little tutorial to change the header and footer of an email. I wanted to know where can I deposit it?
It only takes few sentences. But, I guess a lot of users are looking for that.

**Comment by ywarnier** [comment]
Bonjour, le meilleur endroit s'il s'agit d'un tutoriel textuel et éventuellement quelques images serait le manuel de Chamilo. Si tu t'en sors avec ce qu'on appelle un Pull Request sur Github, tu peux simplement nous l'envoyer de cette manière dans le projet correspondant, quelque part par ici s'il est en anglais: https://github.com/chamilo/docs/tree/1.11.x/en/developer
S'il est en français ça va être un peu plus compliqué parce que nous n'avons pas encore la section "Développeur" en français, mais c'est une question de gestion. Dis-moi ce que tu as.

**Comment by ywarnier** [comment]
Je ferme ceci, mais n'hésites pas (@MonteiroJ ) à contribuer ces tutoriels ici même si tu ne t'en sors pas avec les pull requests
